---
# Setup/install tasks.

- include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Ensure GlusterFS is started / enabled
  service: "name=glusterd state=started enabled=yes"

- name: Recheck for scsi devices
  command: sg_scan
  changed_when: false

- name: Rescan for new disks
  command: /usr/bin/rescan-scsi-bus.sh -a
  changed_when: false

- name: Get partition list
  command: lsblk
  register: lsblk_list
  changed_when: false

- name: Crerate vdo volume(s)
  import_tasks: create-vdo.yml
  when: vdo_create

- name: Create lvm volume(s)
  import_tasks: create-lvm.yml
  when: vdo_create

- name: Mount lvm volume(s)
  import_tasks: mount-lvm.yml
  when: vdo_create

- name: Crerate gluster volume(s)
  import_tasks: create-glusterfs.yml
  when: vdo_create

#- name: Umount lvm volume(s)
#  import_tasks: umount-lvm.yml
#  when: vdo_remove

#- name: Remove vdo volume(s)
#  import_tasks: remove-vdo.yml
#  when: vdo_remove
